dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
env:
  - DJANGO=2.1 DB=default
before_install:
  - sudo apt-get update && apt-get install -y apt-transport-https ca-certificates
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
  - sudo apt-get update
  - ACCEPT_EULA=Y sudo apt-get install -y msodbcsql17 mssql-tools mssql-cli  
  - sudo apt-get install -y unixodbc-dev  
install:
  - pip install -r requirements.txt
before_script:
  - python modules-requirements.py openimis.json > modules-requirements.txt
  - pip install -r modules-requirements.txt
script:
  - cd openIMIS
  - python manage.py test core -n
