language: python
    python:
      - "3.7.2"
    env:
      -DJANGO=2.1 DB=default
    install:
      - pip install -r requirements.txt
    before_script:
      - python modules-requirements.py openimis.json > module-requirements.txt
      - pip install -r module-requirements.txt      
    script:
      - cd openIMIS
      - python manage.py test core -n