language: python
sudo: required
dist: xenial   # required for Python >= 3.7
services:
  - docker
python:
  - "3.7"
env:
  - DJANGO=2.1 DB=default DB_HOST=localhost DB_PORT=1433 DB_NAME=test_db DB_USER=sa DB_PASSWORD=t3sts3cr3tp@ss  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https ca-certificates
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/debian/9/prod.list | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - ACCEPT_EULA=Y sudo apt-get install -y msodbcsql17 mssql-tools mssql-cli
  - sudo ls /opt/microsoft/msodbcsql17/lib64/
  - sudo apt-get install -y python3-dev unixodbc-dev
  - ./script/launch-mssql-in-docker.sh -p $DB_PASSWORD
before_script:
  - pip install -r requirements.txt
  - python modules-requirements.py openimis.json > modules-requirements.txt
  - pip install -r modules-requirements.txt
script:
  - cd openIMIS
  - python manage.py test core -n
